version: '3'

services:
  flaskapp:
    build: ./flask_registration
    ports:
      - "80:80"
    network_mode: host

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    environment:
      - SERVER_NAME=3.86.232.45
    restart: always 
    network_mode: host
