version: '3'

services:
  flaskapp:
    build: ./flask_registration
    container_name: flaskapp1
    #ports:
    #  - "8000:8000"
    #network_mode: host

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    environment:
      - SERVER_NAME=3.95.13.58
    ports:
      - "80:80"
    restart: always 
    #network_mode: host
    
networks:
  default:
    driver: bridge
    

